$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: project-Environment
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20231011.v1
conda_file: conda_envs/python-project-environment.yaml
